<div class="filter-panel" id="filter_panel">
  <div class="panel-info" id="filter_panel__panel_info_1">
    <div class="title">
      <span class="text">DANH MỤC SẢN PHẨM</span>
      <i class="fa fa-angle-down"></i>
    </div>
    <div class="list">
      <a class="item" id="filter_panel__panel_info_1__item">
        Linh kiện tự động hóa
        <input type="checkbox" class="checkbox" value="" id="filter_panel__panel_info_1__item_1__checkbox">
        <label id="filter_panel__panel_info_1__item_1__label" for="filter_panel__panel_info_1__item_1__checkbox">
        </label>
      </a>
      <a class="item" id="filter_panel__panel_info_1__item_2">
        Linh kiện siết
        <input type="checkbox" class="checkbox" value="" id="filter_panel__panel_info_1__item_2__checkbox">
        <label id="filter_panel__panel_info_1__item_2__label" for="filter_panel__panel_info_1__item_2__checkbox">
        </label>
      </a>
      <a class="item" id="filter_panel__panel_info_1__item_3">
        Thiết bị phun cắt
        <input type="checkbox" class="checkbox" value="" id="filter_panel__panel_info_1__item_3__checkbox">
        <label id="filter_panel__panel_info_1__item_3__label" for="filter_panel__panel_info_1__item_3__checkbox">
        </label>
      </a>
      <a class="item" id="filter_panel__panel_info_1__item_4">
        Thiết bị cắt
        <input type="checkbox" class="checkbox" value="" id="filter_panel__panel_info_1__item_4__checkbox">
        <label id="filter_panel__panel_info_1__item_4__label" for="filter_panel__panel_info_1__item_4__checkbox">
        </label>
      </a>
      <a class="item" id="filter_panel__panel_info_1__item_5">
        Thiết bị thủy lực
        <input type="checkbox" class="checkbox" value="" id="filter_panel__panel_info_1__item_5__checkbox">
        <label id="filter_panel__panel_info_1__item_5__label" for="filter_panel__panel_info_1__item_5__checkbox">
        </label>
      </a>
      <a class="item" id="filter_panel__panel_info_1__item_6">
        Dụng cụ dùng điện
        <input type="checkbox" class="checkbox" value="" id="filter_panel__panel_info_1__item_6__checkbox">
        <label id="filter_panel__panel_info_1__item_6__label" for="filter_panel__panel_info_1__item_6__checkbox">
        </label>
      </a>
      <a class="item" id="filter_panel__panel_info_1__item_7">
        Thiết bị hàn
        <input type="checkbox" class="checkbox" value="" id="filter_panel__panel_info_1__item_7__checkbox">
        <label id="filter_panel__panel_info_1__item_7__label" for="filter_panel__panel_info_1__item_7__checkbox">
        </label>
      </a>
    </div>
  </div>

  <div class="panel-info" id="filter_panel__panel_info_2">
    <div class="title">
      <span class="text">NHÀ CUNG CẤP</span>
      <i class="fa fa-angle-down"></i>
    </div>
    <div class="list">
      <a class="item" id="filter_panel__panel_info_2__item">
        A&D
        <input type="checkbox" class="checkbox" value="" id="filter_panel__panel_info_2__item_1__checkbox">
        <label id="filter_panel__panel_info_2__item_1__label" for="filter_panel__panel_info_2__item_1__checkbox">
        </label>
      </a>
      <a class="item" id="filter_panel__panel_info_2__item_2">
        MISUMI
        <input type="checkbox" class="checkbox" value="" id="filter_panel__panel_info_2__item_2__checkbox">
        <label id="filter_panel__panel_info_2__item_2__label" for="filter_panel__panel_info_2__item_2__checkbox">
        </label>
      </a>
      <a class="item" id="filter_panel__panel_info_2__item_3">
        NSK MICRO
        <input type="checkbox" class="checkbox" value="" id="filter_panel__panel_info_2__item_3__checkbox">
        <label id="filter_panel__panel_info_2__item_3__label" for="filter_panel__panel_info_2__item_3__checkbox">
        </label>
      </a>
      <a class="item" id="filter_panel__panel_info_1__item_4">
        FUJI TECH
        <input type="checkbox" class="checkbox" value="" id="filter_panel__panel_info_2__item_4__checkbox">
        <label id="filter_panel__panel_info_2__item_4__label" for="filter_panel__panel_info_2__item_4__checkbox">
        </label>
      </a>
      <a class="item" id="filter_panel__panel_info_2__item_5">
        FUKUHARA
        <input type="checkbox" class="checkbox" value="" id="filter_panel__panel_info_2__item_5__checkbox">
        <label id="filter_panel__panel_info_2__item_5__label" for="filter_panel__panel_info_2__item_5__checkbox">
        </label>
      </a>
    </div>
  </div>

  <div class="panel-info" id="filter_panel__panel_info_3">
      <div class="title">
        <span class="text">GIÁ SẢN PHẨM</span>
        <i class="fa fa-angle-down"></i>
      </div>
      <p class="text">Vui lòng chọn khoảng giá</p>
      <div class="range-slider" id="filter_panel__panel_info_3__range_slider">
        <input type="text" id="filter_panel__panel_info_3__range_slider__input" name="my_range" value="" />
      </div>
      <p class="price">Từ 50.000₫ - 4.000.000₫</p>
      <a href="#" class="button">LỌC</a>
    </div>
</div>