<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
</head>
<body>
<ol>
  <li><a href="home.html">Trang chủ</a></li>
  <li><a href="login.html">Trang Login</a></li>
  <li><a href="forgot-password-1.html">Trang Quên mật khẩu step 1</a></li>
  <li><a href="forgot-password-2.html">Trang Quên mật khẩu step 1</a></li>
  <li><a href="signup.html">Trang đăng kí</a></li>
  <li><a href="product-list.html">Trang danh sách sản phẩm</a></li>
</ol>
</body>
</html>
